# HW3 - Gabriel Santos (santosg2022)
# Custom LangChain agent: RAG custom tool (from hw2) + Terminal tool
"""hw3 custom LangChain agent.

Wraps the hw2 RAG application as a LangChain custom tool and combines it
with LangChain's built-in terminal tool in a Gemini-powered agent, so the
agent can answer security questions from the RAG knowledge base or run
shell commands on the system.

Run this file directly to start an interactive prompt that streams the
agent's tool calls and tool results as they happen.

Configuration is read entirely from environment variables (optionally via
a .env file); no API keys or project IDs are hard-coded here.
"""

import os
import readline  # noqa: F401  (enables line editing and history in input())
import sys

from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain_community.agent_toolkits.load_tools import load_tools
from langchain_core.tools import tool
from langchain_google_genai import ChatGoogleGenerativeAI

# Make the repository root importable so the hw2 package can be found.
# hw2 is imported as a package (hw2.app) rather than adding hw2/ itself to
# sys.path, because both homework directories contain a file named app.py.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hw2.app import build_chain, build_database  # noqa: E402

# Load variables from a local .env file, if present, into the environment.
load_dotenv()

# The RAG chain is built lazily on first use and then reused.
_rag_chain = None


@tool
def rag_search(question: str) -> str:
    """Answer a question using the hw2 RAG document database.

    Use this tool for questions about the documents indexed by the hw2 RAG
    application. On first use, the vector database is populated from
    hw2/rag_data/ if it is empty and the RAG chain is built; later calls
    reuse the same chain.

    Args:
        question: The natural-language question to answer.

    Returns:
        The answer generated from the retrieved document context.
    """
    global _rag_chain
    if _rag_chain is None:
        build_database()
        _rag_chain = build_chain()
    return _rag_chain.invoke(question)


SYSTEM_PROMPT = """You are a helpful security assistant with two tools:

1. rag_search: answers security questions from a RAG knowledge base of
   indexed documents. Use it for questions about security concepts and
   anything covered by those documents.
2. terminal: runs shell commands on the local system. Use it when the user
   asks about this machine (files, processes, network configuration, etc.)
   or when running a command is the best way to get the answer.

Choose the tool that fits the request, base your answer on the tool
results, and say so if neither tool can answer the question. Use at most
8 tool calls per request."""


def build_agent():
    """Create the Gemini agent with the rag_search and terminal tools.

    Returns:
        A tuple (agent, tools) of the compiled agent and its tool list.
    """
    llm = ChatGoogleGenerativeAI(model=os.getenv("GOOGLE_MODEL"))
    tools = [rag_search] + load_tools(["terminal"], allow_dangerous_tools=True)
    agent = create_agent(model=llm, tools=tools, system_prompt=SYSTEM_PROMPT)
    return agent, tools


def print_step(step):
    """Print the model output, tool calls and tool results in one stream step."""
    # 1. Tool calls and text generated by the model.
    if "model" in step:
        for message in step["model"]["messages"]:
            if message.content:
                print(f"🛠️  Content: {message.content}")
            for tool_call in message.tool_calls:
                print(f"🛠️  Tool Call: {tool_call['name']}   Args: {tool_call['args']}")

    # 2. Results returned by the tools.
    if "tools" in step:
        for message in step["tools"]["messages"]:
            print(f"✅ Tool Result: {message.content}")
            print("---")


def main():
    """Build the agent, then run an interactive loop that streams its steps."""
    agent, tools = build_agent()

    print("Welcome to my hw3 agent. I am configured with these tools:")
    for t in tools:
        print(f"  Tool: {t.name} = {t.description}")
    print("Example prompts: What is SQL injection?  |  What is my machine's IP address?")
    print("(blank line to quit)")

    while True:
        try:
            line = input("llm>> ")
            if not line:
                break
            # Stream the agent's steps and print them as they occur.
            for step in agent.stream({"messages": [{"role": "user", "content": line}]}):
                print_step(step)
        except (EOFError, KeyboardInterrupt):
            break
        except Exception as e:
            print(e)


if __name__ == "__main__":
    main()
